### ISSUE TITLE
`SMTIgnoreOS` test setting breaks SMTChecker testing on OSes other than Windows, macOS and Linux

### ISSUE THREAD

**Issue by vtamara** [ethereum/solidity#15679]
## Description

Trying to compile on OpenBSD the `develop` branch advances up to 76% but stops with:

```
[ 76%] Building CXX object test/CMakeFiles/soltest.dir/libsolidity/SMTCheckerTest.cpp.o
/home/vtamara/comp/c++/solidity/test/libsolidity/SMTCheckerTest.cpp:123:26: error: unused variable 'os' [-Werror,-Wunused-variable]
        for (std::string const& os: ignoreOSSetting | ranges::views::split(',') | ranges::to<std::vector<std::string>>())
                                ^
1 error generated.
*** Error 1 in . (test/CMakeFiles/soltest.dir/build.make:1098 'test/CMakeFiles/soltest.dir/libsolidity/SMTCheckerTest.cpp.o': cd /home/vtama...)
*** Error 2 in . (CMakeFiles/Makefile2:785 'test/CMakeFiles/soltest.dir/all': make -s -f test/CMakeFiles/soltest.dir/build.make test/CMakeFi...)
*** Error 2 in /home/vtamara/comp/c++/solidity/build (Makefile:136 'all': make -s -f CMakeFiles/Makefile2 all)
```

## Environment

- Compiler version: clang version 16.0.6
- Target EVM version (as per compiler settings): 
- Framework/IDE (e.g. Truffle or Remix): 
- EVM execution environment / backend / blockchain client:
- Operating system: OpenBSD/adJ 7.6b1

## Steps to Reproduce

```
git clone --recursive https://github.com/ethereum/solidity.git
cd solidity
mkdir build
cd build
cmake ..
make
```

**Comment by cameel** [comment]
This indeed looks like a bug in the test suite. The `SMTIgnoreOS` test setting introduced in #12037 only considers Windows, macOS and Linux and on other platforms the loop variable becomes unused: https://github.com/ethereum/solidity/blob/c3152941e4884d9d9fa35270cc099bf1a237e898/test/libsolidity/SMTCheckerTest.cpp#L122-L135

Not sure if it's worth having BSD as a separate option since we don't have any CI runs for it but we should at least have one covering all OSes not listed explicitly (e.g. `other`).

**Comment by vtamara** [comment]
I confirm that it is working now. Thank you.
