### PR TITLE
Fix some deprecated calls with `boost v1.81`

### PR DESCRIPTION
**Pull request by aarlt**
A build with `boost v1.81` was not possible due to some deprecation warnings.

```
[ 56%] Building CXX object libsolidity/CMakeFiles/solidity.dir/parsing/DocStringParser.cpp.o
/Users/alex/git/solidity/libsolidity/lsp/LanguageServer.cpp:224:27: error: 'recursive_directory_iterator' is deprecated: Use directory_options instead of symlink_option [-Werror,-Wdeprecated-declarations]
        auto directoryIterator = fs::recursive_directory_iterator(m_fileRepository.basePath(), fs::symlink_option::recurse);
                                 ^
/opt/homebrew/include/boost/filesystem/directory.hpp:576:5: note: 'recursive_directory_iterator' has been explicitly marked deprecated here
    BOOST_FILESYSTEM_DETAIL_DEPRECATED("Use directory_options instead of symlink_option")
    ^
/opt/homebrew/include/boost/filesystem/config.hpp:85:64: note: expanded from macro 'BOOST_FILESYSTEM_DETAIL_DEPRECATED'
#define BOOST_FILESYSTEM_DETAIL_DEPRECATED(msg) __attribute__((deprecated(msg)))
                                                               ^
/Users/alex/git/solidity/libsolidity/lsp/LanguageServer.cpp:224:27: error: 'recursive_directory_iterator' is deprecated: Use directory_options instead of symlink_option [-Werror,-Wdeprecated-declarations]
        auto directoryIterator = fs::recursive_directory_iterator(m_fileRepository.basePath(), fs::symlink_option::recurse);
                                 ^
/opt/homebrew/include/boost/filesystem/directory.hpp:576:5: note: 'recursive_directory_iterator' has been explicitly marked deprecated here
    BOOST_FILESYSTEM_DETAIL_DEPRECATED("Use directory_options instead of symlink_option")
    ^
/opt/homebrew/include/boost/filesystem/config.hpp:85:64: note: expanded from macro 'BOOST_FILESYSTEM_DETAIL_DEPRECATED'
#define BOOST_FILESYSTEM_DETAIL_DEPRECATED(msg) __attribute__((deprecated(msg)))
                                                               ^
2 errors generated.
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/lsp/LanguageServer.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
make: *** [all] Error 2
```

```
[ 59%] Building CXX object tools/CMakeFiles/phaser.dir/yulPhaser/Population.cpp.o
/Users/alex/git/solidity/solc/CommandLineInterface.cpp:592:32: error: 'basename' is deprecated: Use path::stem() instead [-Werror,-Wdeprecated-declarations]
        createFile(boost::filesystem::basename(_fileName) + string(".json"), _json);
                                      ^
/opt/homebrew/include/boost/filesystem/convenience.hpp:34:1: note: 'basename' has been explicitly marked deprecated here
BOOST_FILESYSTEM_DETAIL_DEPRECATED("Use path::stem() instead")
^
/opt/homebrew/include/boost/filesystem/config.hpp:85:64: note: expanded from macro 'BOOST_FILESYSTEM_DETAIL_DEPRECATED'
#define BOOST_FILESYSTEM_DETAIL_DEPRECATED(msg) __attribute__((deprecated(msg)))
                                                               ^
1 error generated.
make[2]: *** [solc/CMakeFiles/solcli.dir/CommandLineInterface.cpp.o] Error 1
```

### CODE REVIEW

**Comment by aarlt** [comment]
Hmm.. ok.. that was probably too fast.. this fix breaks the ubuntu build ;)

So I guess we need to have some `#ifdef` magic here....

**Comment by nikola-matic** [comment]
You're a [bit late](https://github.com/ethereum/solidity/pull/13862) @aarlt  :) Gonna close this as a duplicate. In any case, fixing the OSX build by updating the deprecated `boost::filesystem` usage then causes the Ubuntu builds to fail because they're 20.04 and thus use the 1.71.0 version of boost, which has not yet deprecated the offending calls, nor does it contain the better, updated alternatives, which means we have to update the Ubuntu docker images to 22.04 as well (we have PRs for this too).
