### ISSUE TITLE
Compiles but Error: invalid bytecode when trying to deploy

### ISSUE THREAD

**Issue by migoldfinger** [ethereum/solidity#14335]
# Description
I have one specific function which compiles fine but when I try to deploy the contract which it is on with hardhat-deploy I get an Error: invalid bytecode . I do use libraries but these libraries are used in other contracts too without any problem

# Environment
    Compiler version: 0.8.20
    Framework/IDE: hardhat
    EVM execution environment / backend / blockchain client: hardhat network
    Operating system: windows

# Steps to Reproduce
    clone https://github.com/DFX-Protocol/dfx-contracts/tree/stackError
Manual:
    Compile PositionManager contract with hardhat compile using 0.8.20 (solc-js) 
    No compilation error.
    Try to deploy the PositionManager contract with hardhat-deploy
    Get Error: invalid bytecode
Automatic:
    Run npm run deploy:sepolia

**Comment by migoldfinger** [comment]
Found it. There was a library used in the BasePositionManager. Since this is a update attempt there was also an old version of that library with the same name present. Looks like hardhat or solc mixed that up. Since the library uses external functions I think the use as external library is intended. I just did not see (and still do not see) this in the old deploy scripts used for that contract.
