### ISSUE TITLE
Instructions for building with Z3

### ISSUE THREAD

**Issue by maurelian** [ethereum/solidity#3562]
I'm trying to build Solidity with Z3. But it's failing.

## Steps:

1. I [clone, build and install z3](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang). I now have: 

```
$ which z3
 /usr/local/bin/z3
```

2. Clone this repo, checkout `tags/v0.4.18`
3. run `make`

```
[ 61%] Linking CXX executable solc
Undefined symbols for architecture x86_64:
  "_Z3_ast_to_string", referenced from:
      z3::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, z3::ast const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_ast_vector_dec_ref", referenced from:
      z3::ast_vector_tpl<z3::expr>::~ast_vector_tpl() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_ast_vector_get", referenced from:
      z3::ast_vector_tpl<z3::expr>::operator[](int) const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_ast_vector_inc_ref", referenced from:
      z3::ast_vector_tpl<z3::expr>::init(_Z3_ast_vector*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_ast_vector_push", referenced from:
      z3::ast_vector_tpl<z3::expr>::push_back(z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_ast_vector_size", referenced from:
      z3::ast_vector_tpl<z3::expr>::size() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_dec_ref", referenced from:
      z3::ast::~ast() in libsolidity.a(SMTChecker.cpp.o)
      z3::ast::~ast() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_del_config", referenced from:
      z3::config::~config() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_del_context", referenced from:
      z3::context::~context() in libsolidity.a(SMTChecker.cpp.o)
      z3::context::~context() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_get_ast_kind", referenced from:
      z3::cast_ast<z3::expr>::operator()(z3::context&, _Z3_ast*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_get_error_code", referenced from:
      z3::context::check_error() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_get_error_msg", referenced from:
      z3::context::check_error() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_get_sort", referenced from:
      z3::expr::get_sort() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_get_sort_kind", referenced from:
      z3::sort::sort_kind() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_inc_ref", referenced from:
      z3::ast::ast(z3::context&, _Z3_ast*) in libsolidity.a(Z3Interface.cpp.o)
      z3::ast::ast(z3::ast const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_is_re_sort", referenced from:
      z3::concat(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_is_seq_sort", referenced from:
      z3::concat(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_add", referenced from:
      z3::operator+(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_and", referenced from:
      z3::operator&&(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_app", referenced from:
      z3::func_decl::operator()(z3::ast_vector_tpl<z3::expr> const&) const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_ast_vector", referenced from:
      z3::ast_vector_tpl<z3::expr>::ast_vector_tpl(z3::context&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bool_sort", referenced from:
      z3::context::bool_sort() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvadd", referenced from:
      z3::operator+(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvmul", referenced from:
      z3::operator*(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvsge", referenced from:
      z3::operator>=(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvsgt", referenced from:
      z3::operator>(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvsle", referenced from:
      z3::operator<=(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvslt", referenced from:
      z3::operator<(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_bvsub", referenced from:
      z3::operator-(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_concat", referenced from:
      z3::concat(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_config", referenced from:
      z3::config::config() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_const", referenced from:
      z3::context::constant(z3::symbol const&, z3::sort const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_context_rc", referenced from:
      z3::context::init(z3::config&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_eq", referenced from:
      z3::operator==(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_func_decl", referenced from:
      z3::context::function(char const*, z3::sort const&, z3::sort const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_ge", referenced from:
      z3::operator>=(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_gt", referenced from:
      z3::operator>(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_int_sort", referenced from:
      z3::context::int_sort() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_ite", referenced from:
      z3::ite(z3::expr const&, z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_le", referenced from:
      z3::operator<=(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_lt", referenced from:
      z3::operator<(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_mul", referenced from:
      z3::operator*(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_not", referenced from:
      z3::operator!(z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_numeral", referenced from:
      z3::context::int_val(char const*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_or", referenced from:
      z3::operator||(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_re_concat", referenced from:
      z3::concat(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_re_union", referenced from:
      z3::operator+(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_seq_concat", referenced from:
      z3::concat(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_solver", referenced from:
      z3::solver::solver(z3::context&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_string_symbol", referenced from:
      z3::context::str_symbol(char const*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_mk_sub", referenced from:
      z3::operator-(z3::expr const&, z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_model_dec_ref", referenced from:
      z3::model::~model() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_model_eval", referenced from:
      z3::model::eval(z3::expr const&, bool) const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_model_inc_ref", referenced from:
      z3::model::init(_Z3_model*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_set_ast_print_mode", referenced from:
      z3::context::init(z3::config&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_set_error_handler", referenced from:
      z3::context::init(z3::config&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_assert", referenced from:
      z3::solver::add(z3::expr const&) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_check", referenced from:
      z3::solver::check() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_dec_ref", referenced from:
      z3::solver::~solver() in libsolidity.a(SMTChecker.cpp.o)
  "_Z3_solver_get_model", referenced from:
      z3::solver::get_model() const in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_inc_ref", referenced from:
      z3::solver::init(_Z3_solver*) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_pop", referenced from:
      z3::solver::pop(unsigned int) in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_push", referenced from:
      z3::solver::push() in libsolidity.a(Z3Interface.cpp.o)
  "_Z3_solver_reset", referenced from:
      z3::solver::reset() in libsolidity.a(Z3Interface.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [solc/solc] Error 1
make[1]: *** [solc/CMakeFiles/solc.dir/all] Error 2
make: *** [all] Error 2
```

Based on the error... I now have a hunch that I've built z3 wrong for my system, but some guidance for the right way to configure z3, and build solidity with it would be nice. :)

**Comment by axic** [comment]
What version of z3 are you using?

Any particular reason you are using Solidity 0.4.18 and not 0.4.20?

**Comment by maurelian** [comment]
`Z3 version 4.6.1 - 64 bit`

> Any particular reason you are using Solidity 0.4.18 and not 0.4.20?

Only that 0.4.18 was the current version when I first tried this, and it took me a while to return to it. 

It's working in v0.4.20!

**Comment by maurelian** [comment]
Sorry, another question, how would I specify the location that the `solc` executable is built to?

ie. when I install solc normally using homebrew, it's place in /usr/local/Cellar/solidity/0.4.20/bin/solc

I'd like to be able to build locally to /usr/local/Cellar/solidity/0.4.20-z3/bin/solc, so that I can use brew to link it into my path.

**Comment by maurelian** [comment]
I just used a manual symbolic link. 

`ln -s /Users/primary/Projects/solidity/build/solc/solc /usr/local/bin/solc`
