### PR TITLE
Fix shared boost test library build by customizing main

### PR DESCRIPTION
**Pull request by sifmelcara**
### Checklist
- [x] Code compiles correctly
- [x] All tests passing
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary
- [ ] Used meaningful commit messages

### Description

Dynamic linking to boost test was broken by #4572 (which address the misuse of boost unit test library).

Customizing main is needed according to boost document: https://www.boost.org/doc/libs/1_67_0/libs/test/doc/html/boost_test/adv_scenarios/shared_lib_customizations/init_func.html

This patch doesn't affect static link boost build. Not sure if this fix creates potential issue for shared build though.

I use `cmake -DBoost_USE_STATIC_LIBS=OFF -DBUILD_SHARED_LIBS=ON -DINSTALL_LLLC=ON -DCMAKE_CXX_FLAGS="-DBOOST_TEST_DYN_LINK" ..` to configure the build for shared boost libraries.

cc @chfast could you review this change? Thanks very much

### CODE REVIEW

**Review by chfast — COMMENTED** [review]
Can you try to use it also for static linking? 
Do we have `BOOST_TEST_MODULE` defined?

**Comment by sifmelcara** [comment]
@chfast I have tried to make static boost use custom entry function, but keep getting undefined reference error and I have no idea about the correct way to correctly fix it.
```
CMakeFiles/soltest.dir/boostTest.cpp.o:boostTest.cpp:function main: error: undefined reference to 'boost::unit_test::unit_test_main(bool (*)(), int, char**)'
```
Source: https://gist.github.com/sifmelcara/07a36d9615c43556f60946e36d3cdaaa

**Comment by axic** [comment]
@chriseth @ekpyron can you please review this?

File: test/boostTest.cpp [hunk 1]
```diff
@@ -153,3 +153,18 @@ test_suite* init_unit_test_suite( int /*argc*/, char* /*argv*/[] )
...
+#ifdef BOOST_TEST_DYN_LINK
+
+// Because we want to have customized initialization function and support shared boost libraries at the same time,
+// we are forced to customize the entry point.
+// see: https://www.boost.org/doc/libs/1_67_0/libs/test/doc/html/boost_test/adv_scenarios/shared_lib_customizations/init_func.html
+
+int main(int argc, char* argv[])
+{
+	auto init_unit_test = []() -> bool { init_unit_test_suite(0, nullptr); return true; };
+	return boost::unit_test::unit_test_main( init_unit_test, argc, argv );
```
Comment (axic) [inline test/boostTest.cpp]: Please fix indentation here (no spaces around parentheses).

**Comment by axic** [comment]
Checked the linked documentation and this seems to be correct way.

What is a bit more worrying is that our initialisation function is kind of obsolete (but still works): https://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/adv_scenarios/obsolete_init_func.html

**Review by axic — DISMISSED** [review]

**Review by ekpyron — CHANGES_REQUESTED** [review]
This looks good in general, but building ``soltest`` still fails with ``cmake -DBoost_USE_STATIC_LIBS=OFF ..`` without also using ``-DCMAKE_CXX_FLAGS="-DBOOST_TEST_DYN_LINK"``, so I think we should add ``BOOST_TEST_DYN_LINK`` to ``CMAKE_CXX_FLAGS`` by default if ``Boost_USE_STATIC_LIBS`` is set to ``OFF``.

Probably something like
```
  if (NOT Boost_USE_STATIC_LIBS)
    target_compile_definitions(soltest PUBLIC -DBOOST_TEST_DYN_LINK)
endif()
```
in ``test/CMakeLists.txt`` after ``add_executable(soltest ...)`` will suffice (we only need the flag for building ``soltest``).

**Review by ekpyron — APPROVED** [review]

**Comment by ekpyron** [comment]
I added the small change to ``test/CMakeLists.txt`` myself.

**Comment by axic** [comment]
> Do we have `BOOST_TEST_MODULE` defined?

@chfast no, checked it.

**Comment by axic** [comment]
@ekpyron actually should have a CI task to build it in shared mode?

**Comment by ekpyron** [comment]
@axic It might be a good idea - I'll open an issue for it.

**Comment by ekpyron** [comment]
@axic Why do we actually statically link to boost by default in the first place? We may want to do that for binary releases, but I don't think it should be the default...

**Comment by axic** [comment]
I'm not sure.

**Comment by ekpyron** [comment]
@axic OK - we can consider changing it in #4660.

**Comment by sifmelcara** [comment]
Maybe we should merge this PR before #4660 is addressed? (I saw #4660 tagged with `0.5.1` tag, and we probably want this PR be part of 0.5.0 release because many distros prefers dynamic linking to boost)

**Comment by chriseth** [comment]
0.5.0 should be as smooth as possible, I fear we already did too many changes to the build system for such an important release. I'm almost certain that 0.5.1 (meaning a small bugfix release) will follow shortly after 0.5.0 :(

**Review by axic — APPROVED** [review]

File: test/CMakeLists.txt [hunk 2]
```diff
@@ -24,4 +24,8 @@ add_executable(soltest ${sources} ${headers}
 )
 target_link_libraries(soltest PRIVATE libsolc solidity lll evmasm devcore ${Boost_UNIT_TEST_FRAMEWORK_LIBRARIES})
 
+if (NOT Boost_USE_STATIC_LIBS)
```
Comment (chfast) [inline test/CMakeLists.txt:27]: Where is this variable defined? It should be a _cache_ variable if you want to change the value with command line options.

File: test/boostTest.cpp [hunk 3]
```diff
@@ -153,3 +153,18 @@ test_suite* init_unit_test_suite( int /*argc*/, char* /*argv*/[] )
...
 }
+
+// BOOST_TEST_DYN_LINK should be defined if user want to link against shared boost test library
+#ifdef BOOST_TEST_DYN_LINK
+
+// Because we want to have customized initialization function and support shared boost libraries at the same time,
+// we are forced to customize the entry point.
+// see: https://www.boost.org/doc/libs/1_67_0/libs/test/doc/html/boost_test/adv_scenarios/shared_lib_customizations/init_func.html
+
+int main(int argc, char* argv[])
```
Comment (chfast) [inline test/boostTest.cpp:164]: Still no way to _always_ use the custom main function?

Comment (axic) [reply test/boostTest.cpp:164]: Read the linked URL. It is deprecated.

Comment (chfast) [reply test/boostTest.cpp:164]: It only states you have to use custom entry point for shared libs. But nothing prevents you from using it for static libs as well.

File: test/CMakeLists.txt (hunk 2 above)
Comment (ekpyron) [reply test/CMakeLists.txt:27]: https://github.com/ethereum/solidity/blob/8b2d630275fb29d2915af76f608be4d4e422907f/cmake/EthDependencies.cmake#L39

Comment (chfast) [reply test/CMakeLists.txt:27]: This is ok then.

**Comment by ekpyron** [comment]
@chriseth Well, this change is pretty harmless - it should affect only cases that are broken right now anyways and as @sifmelcara points out, it may be good to have shared linking support as fixed up again as soon as possible, so I'd vote for merging this in 0.5.0.

**Comment by chriseth** [comment]
@ekpyron I agree, this is not the problematic PR ;)

File: test/boostTest.cpp (hunk 3 above)
Comment (ekpyron) [reply test/boostTest.cpp:164]: We should probably look into that, but maybe we should create another issue for overhauling all these parts of the boost test setup (@axic already noted somewhere that we use deprecated features anyways) and queue that for 0.5.1 instead?

Comment (ekpyron) [reply test/boostTest.cpp:164]: Tracked in #4730 now.

**Comment by axic** [comment]
@chfast and objection to merging this?

**Review by chfast — APPROVED** [review]
No.
