### PR TITLE
Enable the -Wextra-semi warning

### PR DESCRIPTION
**Pull request by axic**
Picked from #10264
Part of #6905.

Feel free to close if disagreeing with it.

### CODE REVIEW

**Comment by mijovic** [comment]
I don't see why we shouldn't try enabling all of extra warnings. This looks fine, but looks like some compilers doesn't recognize this option.

**Comment by axic** [comment]
> I don't see why we shouldn't try enabling all of extra warnings. 

Well in #10264 you can see that just enabling conversion warnings triggers a compiler bug 😕 

And on this PR it is the same compiler which complains. Cursed ubuntu18.

**Comment by cameel** [comment]
Maybe GCC on Ubuntu 18 is too old? The flag was added in GCC 8.1 according to [WarningHistory](https://gcc.gnu.org/wiki/WarningHistory).

**Comment by cameel** [comment]
Also there used to be some wonky behavior between systems. See for example [-Wextra-semi causes build failure on debian bullseye](https://ea5faa5po25cf7fb.onion.ly/projects/tor/ticket/31769). Hopefully that's fixed now but it may still be an issue with older versions.

**Comment by axic** [comment]
> Maybe GCC on Ubuntu 18 is too old? The flag was added in GCC 8.1 according to WarningHistory.

Yeah but it is conditionally enabled whether the compiler supports it or not. Just even that fails on ubuntu 18.

**Comment by leonardoalt** [comment]
Is it a cmake or gcc bug?

**Comment by axic** [comment]
> Is it a cmake or gcc bug?

Hm, good idea, it may be a shortcoming in the old cmake Ubuntu 18 uses (3.10.2).

`b_ubu_clang` uses clang and cmake 3.16, `b_archlinux` uses gcc and cmake 3.19.

As far as I can tell it should work at least with cmake 3.3+, but Ubuntu 18... so how about if we disable it?

**Comment by leonardoalt** [comment]
I think we talked about removing Ubuntu 18.04 before? I'd support it. We don't even use the `b_ubu18` build for tests

**Comment by axic** [comment]
Seems to be working:
```
[ 37%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ControlFlowAnalyzer.cpp.o
[ 38%] Building CXX object libsolidity/CMakeFiles/solidity.dir/analysis/ControlFlowBuilder.cpp.o
In file included from /root/project/libsolidity/analysis/ControlFlowAnalyzer.h:21,
                 from /root/project/libsolidity/analysis/ControlFlowAnalyzer.cpp:19:
/root/project/libsolidity/analysis/ControlFlowGraph.h:79:48: error: extra ‘;’ after in-class function definition [-Werror=extra-semi]
   79 |  Kind kind() const { return m_occurrenceKind; };
      |                                                ^
      |                                                -
```

**Comment by axic** [comment]
Removed commit 9045339, should be ready for merge.

**Review by mijovic — DISMISSED** [review]
Spellcheck error was fixed on develop by @leonardoalt so it's good to merge

File: cmake/EthCompilerSettings.cmake [hunk 1]
```diff
@@ -52,6 +52,13 @@ if (("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU") OR ("${CMAKE_CXX_COMPILER_ID}" MA
 	add_compile_options(-Wimplicit-fallthrough)
 	add_compile_options(-Wsign-conversion)
 
+	# While this should work on CMake 3.3+, it fails on Ubuntu 18
+	if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.16)
```
Comment (cameel) [inline cmake/EthCompilerSettings.cmake:56]:
```suggestion
	if (CMAKE_VERSION VERSION_GREATER_EQUAL 3.16)
```

File: cmake/EthCheckCXXCompilerFlag.cmake [hunk 2]
```diff
@@ -10,9 +10,7 @@ include(CheckCXXCompilerFlag)
 #
 function(eth_add_cxx_compiler_flag_if_supported FLAG)
   # Remove leading - or / from the flag name.
-  string(REGEX REPLACE "^[-/]" "" name ${FLAG})
-  # Deletes any ':' because it's invalid variable names.
-  string(REGEX REPLACE ":" "" name ${name})
+  string(REGEX REPLACE "^-|/" "" name ${FLAG})
```
Comment (cameel) [inline cmake/EthCheckCXXCompilerFlag.cmake]: Won't this regex just match `/` at any position rather than at the beginning of the option? Tests are passing so probably not but maybe that's just because most options passed to this already start with `-`?

```suggestion
  string(REGEX REPLACE "^(-|/)" "" name ${FLAG})
```

File: cmake/EthCompilerSettings.cmake (hunk 1 above)
Comment (axic) [reply cmake/EthCompilerSettings.cmake:56]: All our cmake files follow this style, i'd say >95% of the time. I don't care which though.

Comment (cameel) [reply cmake/EthCompilerSettings.cmake:56]: Oh. And I specifically looked the whole file to make sure I'm not suggesting something out of line. Well, looks like this file is an exception then :) Disregard my comment in that case. I thought it was more consistent in the code base.

Comment (axic) [reply cmake/EthCompilerSettings.cmake:56]: Yes, it seems this file is nicer, i'll change it.

**Comment by leonardoalt** [comment]
Still needs rebase

**Comment by leonardoalt** [comment]
Rebased

File: cmake/EthCheckCXXCompilerFlag.cmake [hunk 3]
```diff
@@ -10,9 +10,7 @@ include(CheckCXXCompilerFlag)
 #
 function(eth_add_cxx_compiler_flag_if_supported FLAG)
   # Remove leading - or / from the flag name.
-  string(REGEX REPLACE "^[-/]" "" name ${FLAG})
-  # Deletes any ':' because it's invalid variable names.
-  string(REGEX REPLACE ":" "" name ${name})
```
Comment (ekpyron) [inline cmake/EthCheckCXXCompilerFlag.cmake]: We can't just remove this, this will break windows builds under some circumstances.

I.e. in VisualStudio builds ``CMAKE_SOURCE_DIR`` can end up being an absolute path with a drive name colon - and the presence of that will break https://github.com/ethereum/solidity/blob/eb77ed080a44c456caedde666e8af813685a16f4/cmake/EthCompilerSettings.cmake#L29

File: cmake/EthCheckCXXCompilerFlag.cmake (hunk 2 above)
Comment (ekpyron) [reply cmake/EthCheckCXXCompilerFlag.cmake]: This will also, in general break https://github.com/ethereum/solidity/blob/eb77ed080a44c456caedde666e8af813685a16f4/cmake/EthCompilerSettings.cmake#L29

Comment (ekpyron) [reply cmake/EthCheckCXXCompilerFlag.cmake]: Or depends... ah well... all of this is a mess in general :-D...

Comment (ekpyron) [reply cmake/EthCheckCXXCompilerFlag.cmake]: But yeah, the current version in the PR will remove all ``/`` in ``${CMAKE_SOURCE_DIR}``, which will result in the macro prefix option to stop matching the actual source dir, leading to that ending up in the binaries again in the end, avoiding which is the whole point of the macro-prefix option thing. So that's not good at least...

Comment (ekpyron) [reply cmake/EthCheckCXXCompilerFlag.cmake]: In general I'm not sure if there are any or many compiler options that we pass in here and that start with a ``-`` that will end up being valid MSVC options, if they start with ``/`` instead...

**Comment by ekpyron** [comment]
Rebased and dropped the second commit to see if that fails anywhere.

**Comment by chriseth** [comment]
Does not seem to fail.

**Review by ekpyron — APPROVED** [review]
If we go for https://github.com/ethereum/solidity/pull/10499 we could probably drop the weird cmake version workaround as well.

**Comment by ekpyron** [comment]
Tests are passing, I'll just merge this and rebase #10499, removing the workaround there.
