### ISSUE TITLE
ABIEncoderV2 runs into stack too deep

### ISSUE THREAD

**Issue by mudgen** [ethereum/solidity#10930]
This code will not compile using Solidity 0.8.1 and with compiler optimizations on:
```Solidity
// SPDX-License-Identifier: MIT
pragma solidity 0.8.1;

/******************************************************************************\
* Author: Nick Mudge
*
* Implementation of an example of a diamond.
/******************************************************************************/

enum FacetCutAction {Add, Replace, Remove}

struct FacetCut {
    address facetAddress;
    FacetCutAction action;
    bytes4[] functionSelectors;
}

contract GHSTDiamond {
    struct ConstructorArgs {
        address owner;
    }

    constructor(FacetCut[] memory _diamondCut, ConstructorArgs memory _args) {}
}
```
But this same code does compile with no problem if compiler optimization is turned off or if it is compiled using Solidity 0.7.6 with `pragma abicoder v2;` and with compiler optimization turned on.

This is the error I get:
```Solidity
CompilerError: Stack too deep when compiling inline assembly: Variable dataEnd is 1 slot(s) too deep inside the stack.
Error HH600: Compilation failed
```

**Comment by chriseth** [comment]
Simplified to
```
struct FacetCut {
    bytes4[] functionSelectors;
}

struct ConstructorArgs {
    address owner;
}

contract GHSTDiamond {
    constructor(FacetCut[] memory _diamondCut, ConstructorArgs memory _args) {}
}
```
The issue is not the compiler version but ABI coder v2 - it also fails in 0.7.x with abi v2 activated.

**Comment by mudgen** [comment]
@chriseth Is `pragma experimental ABIEncoderV2;`   different than ABI coder v2?

Because it works with 0.7.* and `pragma experimental ABIEncoderV2;`

**Comment by chriseth** [comment]
For me it fails starting from 0.7.2, regardless of the pragma.

**Comment by chriseth** [comment]
It is really weird why this optimizes so badly. What is the case is that the two return variables are only assigned at the very end, so this might work again when we change the stack allocation as we planned @ekpyron

**Comment by chriseth** [comment]
I think this is a case where a function that is only used once is forcibly inlined even though the function it is inlined into is already quite large. So this could work again if the code is larger.

**Comment by Ungolim** [comment]
> I think this is a case where a function that is only used once is forcibly inlined even though the function it is inlined into is already quite large. So this could work again if the code is larger.

So we should just turn off the optimizer for now?

**Comment by hrkrshnn** [comment]
@lepidotteri Do you get the same issue for the full contract? If yes, you could try turning off just the yul optimizer with `--no-yul-optimize`.

**Comment by drortirosh** [comment]
how about adding "`@inline`" and "`@noinline`" optimizer hints and avoid (or limit) heuristics in those cases.
C/C++ compilers had it for a long time - sometimes the developer knows better than the compiler the better approach.

**Comment by hrkrshnn** [comment]
@drortirosh Doesn't C++ compilers mostly ignore the `inline` hints? Anyway, this was bought up before, and we generally wanted the optimizer to be independent of user inputs like these; however we do allow users to specify an optimization sequence using `--yul-optimizations="..."`.

Even if `inline` hints are implemented, it would just be extremely tricky for users to reason what should and should not be inlined.

**Comment by hrkrshnn** [comment]
[Here](https://gist.github.com/hrkrshnn/b999b8d53ddf179167cdd6928e467068) is a diff between the ir generated between 0.8.0 and 0.8.1. The main difference is the function

```
        function round_up_to_mul_of_32(value) -> result {
            result := and(add(value, 31), not(31))
        }
```

Instead of allocating `size`, we allocate `round_up_to_mul(size)`.

**Comment by drortirosh** [comment]
> Anyway, this was bought up before, and we generally wanted the optimizer to be independent of user inputs like these; however we do allow users to specify an optimization sequence using `--yul-optimizations="..."`.

Command line options are an all-or-nothing solution. They don't allow a developer to specify a place where optimization is required.
E.g there is no way to trade runtime vs construction-time cost

**Comment by chriseth** [comment]
Please don't pollute this issue. `@inline` or `@noinline` will not solve this because the inlined function is a low-level function that has no counterpart in the Solidity source.

**Comment by mallapurbharat** [comment]
I found this bug while searching for the "slot too deep inside the stack" error.

I am facing the same issue when trying to use Truffle compile the below source. I was trying to see how many value type arguments can be passed to a function. The solidity documentation seems to suggest that 16 arguments should be accessible. However, I found that only 11 seem to be accepted in 0.8.1 whereas 0.7.6 allows up to 16 arguments as expected!

**When Compiled with 0.8.1 of solc I get : 
_Error: CompileError: CompilerError: Stack too deep when compiling inline assembly: Variable headStart is 1 slot(s) too deep inside the stack._**

**If I switch to 0.7.6 of solc, I get "Compiled successfully using: solc: 0.7.6+commit.7338295f.Emscripten.clang"**

Also, it **compiles successfully in 0.7.6 without the "pragma experimental ABIEncoderV2;" as well**!

```
//SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;
contract DoesNotCompile {    
    uint u;
    function fStackLimit(uint u1, uint u2, uint u3, uint u4, uint u5, uint u6, uint u7, uint u8, uint u9, uint u10, uint u11, uint u12) public {        
    }
}
```

**NOTE: However, as expected, removing the uint u12 parameter from the function call seems to fix this error in 0.8.1**

**Comment by chriseth** [comment]
@mallapurbharat stack access is more complicated and depending on the context, the limit is hit earlier sometimes.

**Comment by rriescog** [comment]
Any news of the resolution of this issue? @cameel ? @chriseth ? Thanks!

**Comment by mudgen** [comment]
Are there plans to resolve this issue?

**Comment by cameel** [comment]
There are. Solving stack issues in general is one of the priority tasks right now. The work on the new codegen is ongoing in #11080 (issue) and #11493, #11525, #11615 (PRs). Also #10015, which will land in the next release, might help here.

If this particular piece of code compiled on 0.7.6 it's a regression but it's most likely a consequence of other changes that were done in the codegen in the meantime to help with stack problems. Trying to target this specific regression is pointless since it will just make the problems return in other situations and might not even be possible without just reverting these changes which we will not do.

The stack issues are an inherent limitation of the EVM (only 16 stack slots are reachable at any given moment) and all we can do is add features that work around that limitation. #10015 is a mechanism for moving variables from stack to memory. @ekpyron is also currently working on a better Yul->EVM code generator. Both of these are for the new Yul-based pipeline so they won't solve the general "stack too deep" issue in the old codegen but ABI Encoder v2 works by generating Yul code so I think they will at least help with the issue you're seeing.

**Comment by mudgen** [comment]
@cameel This is great. Thank you!

**Comment by mudgen** [comment]
Hello, are there any updates in progress concerning this?   I ran into a problem recently where it would be really useful if this issue was fixed.

**Comment by ekpyron** [comment]
The examples in this issue seem to compile with both ``solc --optimize --bin`` as well as ``solc --optimize --experimental-via-ir --bin`` both with 0.8.12 and current ``develop``.

So we do make continuous progress on this, but there will still be cases in which such errors are unavoidable (ultimately the reason for these errors is the fact that the EVM only provides limited stack access, so all we can do is try to work around this where possible).
In the near future we expect that ``solc --optimize --experimental-via-ir --bin`` (which will also hopefully be marked non-experimental in the near future) when using only memory-safe inline assembly (https://github.com/ethereum/solidity/pull/12620, resp. https://github.com/ethereum/solidity/pull/12663) will only very rarely exhibit stack errors (the only remaining cases should be in stack-heavy recursive functions).

**Comment by mudgen** [comment]
@ekpyron cool, thanks for that update and info. Much appreciated.

**Comment by cameel** [comment]
This should be solved now. Starting with 0.8.13 the IR-based code generator is no longer an experimental feature. If anyone is still getting "Stack too deep" errors when using `--via-ir --optimize`, please report it as a separate issue and we'll investigate.

**Comment by drortirosh** [comment]
How do you use this --via-ir with etherscan verification ?

**Comment by hrkrshnn** [comment]
@drortirosh The argument can go into the standard json setting in your framework and then use etherscan verification. As an example, see: https://etherscan.io/address/0x00000000006cee72100d161c57ada5bb2be1ca79#code
