### ISSUE TITLE
External test for Gnosis Protocol v2 fails with `TypeError: authenticator.connect is not a function` and other errors

### ISSUE THREAD

**Issue by Marenz** [ethereum/solidity#13228]
https://app.circleci.com/pipelines/github/ethereum/solidity/24994/workflows/03537476-6acb-4266-824e-f0b89854df3c/jobs/1100938

The repo hasn't changed so maybe something on our end broke it?
Finding the offending commit might help

**Comment by Marenz** [comment]
fyi, we currently pinpointed this to the last working commit, but this still needs doing.

[Edit] Confused the issue, disregard.

**Comment by cameel** [comment]
It's weird then. I see that the test still points at `main` branch of the [gp-v2-contracts](https://github.com/gnosis/gp-v2-contracts) repo and that did not have any new commits recently (in fact the repo archived and I was going to submit a PR to switch to the new one but that's a separate matter).

So why did it stop failing? Was it just a one-off problem?

**Comment by cameel** [comment]
To make finding it easier in the future, the specific error messages that this problem caused in [1100938](https://app.circleci.com/pipelines/github/ethereum/solidity/24994/workflows/03537476-6acb-4266-824e-f0b89854df3c/jobs/1100938):

```
  187 passing (1m)
  2 pending
  87 failing

  1) AllowListStorageReader
       areSolvers
         returns true when all specified addresses are solvers:
     TypeError: authenticator.connect is not a function

...

  3) E2E: Can settle a 0x trade
       "before each" hook for "should settle an EOA trade with a 0x trade":
     ERROR processing /tmp/ext-test-Gnosis-Protocol-V2-AjPlM1/ext/src/deploy/001_authenticator.ts:
Error: ENOENT: no such file or directory, open '/home/circleci/.tenderly/config.yaml'

...

  85) Task: withdraw
       "after each" hook for "should withdraw tokens from the settlement contract":
     AssertionError: Unspecified AssertionError
...
```

**Comment by Marenz** [comment]
Sorry, I confused the issue with the ens external test

**Comment by cameel** [comment]
Ah, ok then. So I guess this one got fixed on its own?
Could have been a bug in some dependency or Hardhat that just got fixed quickly.

**Comment by Marenz** [comment]
> Ah, ok then. So I guess this one got fixed on its own?

Hu, seems so. Nice.

**Comment by cameel** [comment]
ok, then I'm closing this :)
