### ISSUE TITLE
Tracking Solidity 0.5.0 support

### ISSUE THREAD

**Issue by axic** [ethereum/solidity#5422]
It is likely that no tool is working correctly with Solidity 0.5.0 yet.

Relevant issues:
- https://github.com/ethereum/remix-ide/issues/1607 (and https://github.com/ethereum/remix-ide/issues/1606) -- DONE (Remix 0.7.5 - live)
- https://github.com/embark-framework/embark/issues/1081  -- DONE (Embark 3.2.4)
- https://github.com/trufflesuite/truffle/issues/1436 (and https://github.com/trufflesuite/truffle/issues/1426) -- DONE
- https://github.com/OpenZeppelin/openzeppelin-solidity/issues/1498 (and https://github.com/OpenZeppelin/openzeppelin-solidity/pull/1496) - DONE (Zeppelin 2.1)

**Comment by ipatka** [comment]
I'm trying to use Truffle 5.0.0 with Solc 0.5.0 and I get an error when I try to compile. Maybe this is related


```
TypeError: Error parsing /Users/.../AccountRegistry.sol: solc.compileStandard is not a function
    at Object.parseImports (/Users/.../node_modules/truffle/build/webpack:/packages/truffle-compile/parser.js:49:1)
    at Object.getImports (/Users/.../node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:332:1)
    at Promise.all.then.results (/Users/.../node_modules/truffle/build/webpack:/packages/truffle-compile/profiler.js:305:1)
    at <anonymous>
```

truffle.js
```
  compilers: {
    solc: {
      version: "0.5.0"
    }
  },
```

**Comment by gnidan** [comment]
@ipatka You can track the fix for that issue in Truffle at trufflesuite/truffle#1435

**Comment by axic** [comment]
Truffle made a nightly 5.x release working with Solidity 0.5.0.

Embark has it merged, but release is yet to come.

Remix has in released on the Alpha version.

**Comment by LianaHus** [comment]
and we have a  Remix-ide release https://github.com/ethereum/remix-ide/releases/tag/v0.7.5

**Comment by axic** [comment]
Oraclize has 0.5.0 support now: https://github.com/oraclize/ethereum-api/pull/67

**Comment by axic** [comment]
Zeppelin has done it with 2.1: https://github.com/OpenZeppelin/openzeppelin-solidity/releases/tag/v2.1.1
