### ISSUE TITLE
Compile failed, got  "ld: 31 duplicate symbols for architecture x86_64"

### ISSUE THREAD

**Issue by duanbing** [ethereum/solidity#3845]
I tried to build solidity from source code on my MacOS following those steps:
```
$ cd $SOURCE_DIR
$ mkdir build && cd build && cmake         # all successed
$ make               #output as below
....
[100%] Linking CXX executable soltest
duplicate symbol __ZNK5boost9unit_test9framework17context_generator8is_emptyEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework11get_contextEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZNK5boost9unit_test9framework17context_generator4nextEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework17current_test_unitEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework16test_in_progressEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework4impl13setup_loggersEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework5clearEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework8shutdownEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework17master_test_suiteEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework17current_test_caseEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework20current_test_case_idEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework12test_abortedEv in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework20finalize_setup_phaseEm in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework13clear_contextEi in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework3runEmb in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework3runEPKNS0_9test_unitEb in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework11add_contextERKNS0_12lazy_ostreamEb in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework23current_auto_test_suiteEPNS0_10test_suiteEb in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework4initEPFPNS0_10test_suiteEiPPcEiS5_ in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework16assertion_resultENS0_16assertion_resultE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework20deregister_test_unitEPNS0_9test_unitE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework4impl19setup_for_executionERKNS0_9test_unitE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework17test_unit_abortedERKNS0_9test_unitE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework19deregister_observerERNS0_13test_observerE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework17register_observerERNS0_13test_observerE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework16exception_caughtERKNS_19execution_exceptionE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework18register_test_unitEPNS0_10test_suiteE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework18register_test_unitEPNS0_9test_caseE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework25deregister_global_fixtureERNS0_17test_unit_fixtureE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework23register_global_fixtureERNS0_17test_unit_fixtureE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
duplicate symbol __ZN5boost9unit_test9framework3getEmNS0_14test_unit_typeE in:
    CMakeFiles/soltest.dir/boostTest.cpp.o
    /usr/local/lib/libboost_unit_test_framework-mt.a(framework.o)
ld: 31 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/soltest] Error 1
make[1]: *** [test/CMakeFiles/soltest.dir/all] Error 2
make: *** [all] Error 2
```
Any one met the same problem?

**Comment by axic** [comment]
I do not have this problem on a Mac, what version of boost and macos do you have?

**Comment by duanbing** [comment]
@axic Thanks for your replying. MacOS version is 10.13.3 (17D47), boost is `#define BOOST_VERSION 106600`

**Comment by kasima** [comment]
I'm having the same issue on 10.13.4, boost 1.66.0 from homebrew.

**Comment by kasima** [comment]
I was able to get everything built from source from the `v0.4.21` tag, with [boost 1.65.1 from howebrew](https://github.com/Homebrew/homebrew-core/commit/146b36f08b6e466d01e2c9cb9f618efac0bf72fa#diff-5148b5dd1fa3716ad2777ce49eaf03a9):

`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/146b36f08b6e466d01e2c9cb9f618efac0bf72fa/Formula/boost.rb`

**Comment by duanbing** [comment]
@kasima Thanks, solved by your way.

**Comment by yusinto** [comment]
> I was able to get everything built from source from the v0.4.21 tag, with boost 1.65.1 from howebrew

@kasima works for me too. Thanks!

**Comment by axic** [comment]
@kasima @duanbing are you saying that it fails with boost 1.66.0 but works with 1.65.1?

I have 1.66.0 myself on mac and it seems to be working.

**Comment by kasima** [comment]
@axic – That's right. I'm building on a brand new installation of OS X 10.13.4, with no previous versions of solidity or homebrew. Maybe the OS version has something to do with it?

**Comment by lixuan1** [comment]
This is a conflict caused by the executable file.Modify the add_executable() parameter in the CMakeLists.txt file, and delete the .cpp except main.cpp from the parameter.
